### ISSUE TITLE
[question] can you do this in version 1.19.2?

### ISSUE THREAD

**Issue by MrSmi1ey** [JustAlittleWolf/fabricForceLowercase#1]

**Comment by JustAlittleWolf** [comment]
Sorry, not in the near future. The chat system changed a lot in between 1.19.2 and 1.19.4 and I don't want to go through the hassle to correct it at the moment. You do it yourself and open a pullrequest if you want to.

**Comment by MrSmi1ey** [comment]
Thank you for answering my question
